<a href="https://colab.research.google.com/github/anshudahiya121/Python_1/blob/main/Python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [ ]:
import numpy as np
names=np.array(['Bob','Will','Joe','Bob','Will','Joe','Joe'])
print(names)
print(names[2])


['Bob' 'Will' 'Joe' 'Bob' 'Will' 'Joe' 'Joe']
Joe


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[2])

30


In [ ]:
import numpy as np
names=np.array(['Aman','sita','geeta','sita'])
print(names[[0,2]])


['Aman' 'geeta']


In [ ]:
import numpy as np
arr=np.array([10,20,30])
print(arr.shape)


(3,)


Wap to find 1D array

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Array:",arr)
print("Dimensions:",arr.ndim)

Array: [10 20 30 40 50]
Dimensions: 1


In [ ]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(arr)

[[10 20 30]
 [40 50 60]]


In [ ]:
import numpy as np
names=np.array([['Aman','sita','geeta',],['sita','geeta','sita']])
print(names)

[['Aman' 'sita' 'geeta']
 ['sita' 'geeta' 'sita']]


In [ ]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0, 1])

20


In [ ]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(arr[1,[1,2]])

[50 60]


print 1st row


In [ ]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr[0])


[10 20 30]


2nd colmn


In [ ]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr[:, 1])

[20 50]


sum of all elements


In [ ]:
import numpy as np
arr=np.array([[25,30,27],[15,18,14]])
print(np.sum(arr))

129


In [ ]:
import numpy as np
arr=np.array([15,20,25,30])
print(np.sum(arr))

90


find min n max of array
1st..20,37,15...2nd..5,23,55

In [ ]:
import numpy as np
arr=np.array([[20,37,15],[5,23,55]])
print(np.min(arr))
print(np.max(arr))

5
55


a=15,25,35
b=4,5,7

In [ ]:
import numpy as np
a=np.array([15,25,35])
b=np.array([4,5,7])
print(np.add(a,b))

[19 30 42]


In [ ]:
import numpy as np
a=np.array([15,25,35])
b=np.array([4,5,7])
print(np.subtract(a,b))

[11 20 28]


In [ ]:
import numpy as np
a=np.array([15,25,35])
b=np.array([4,5,7])
print(np.subtract(b,a))

[-11 -20 -28]


add two 2d array
1st
1,2
3,4
2nd
5,6
7,8

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.add(arr1,arr2)
print(result)


[[ 6  8]
 [10 12]]


Wap to multiply a array 1D
1=7,8,9 with 2


In [ ]:
import numpy as np
a=np.array([7,8,9])
print(a*2)


[14 16 18]


multipy
1,2
3,4 with 5

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a*5)

[[ 5 10]
 [15 20]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.multiply(a,b))

[[ 5 12]
 [21 32]]


WAP to slice the variable 1-4 out of 5 elemnts

In [ ]:
import numpy as np
arr=np.array([5,7,8,9,6])
print(arr[1:4])

[7 8 9]


In [ ]:
import numpy as np
arr=np.array([5,7,8,9,6])
print(arr[2:5])

[8 9 6]


to get every second element


In [ ]:
import numpy as np
arr=np.array([5,7,8,9,6])
print(arr[::2])

[5 8 6]


to reverse the aray

In [ ]:
import numpy as np
arr=np.array([2,4,6,8])
rev=arr[::-1]
print(rev)


[8 6 4 2]


to find sum n avg of 1 D  arr ...12,15,20,23,42

In [ ]:
import numpy as np
arr=np.array([12,15,20,23,42])
sum=np.sum(arr)
avg=sum/len(arr)
print(sum)
print(avg)


112
22.4


1.WAp for string array operation str= aman rahul priya simran ..convert all in uppercase , print 1st n last name, find total no. of names

In [ ]:
import numpy as np
str=np.array(['aman','rahul','priya','simran'])
print(np.char.upper(str))
print(str[0])
print(str[-1])
print(len(str))

['AMAN' 'RAHUL' 'PRIYA' 'SIMRAN']
aman
simran
4


Create an array from 1to24 and reshape it into 6row 4 column ,print first row ,last row,3rd colmn,last 2rows

In [ ]:
import numpy as np
arr = np.arange(1, 25).reshape(6, 4)
print(arr)
print(arr[0])
print(arr[-1])
print(arr[:, 2])
print(arr[4:])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[1 2 3 4]
[21 22 23 24]
[ 3  7 11 15 19 23]
[[17 18 19 20]
 [21 22 23 24]]


WAP in array 45,67,89,34,90,56,78,99 find i.)scores above 75 ii.)less then 40 fail iii.)total number of elements in array

In [ ]:
import numpy as np
marks=np.array([45,67,89,34,90,56,78,99])
print(len((marks)[marks>75]))
print(len((marks)[marks<40]))
print(len(marks))

4
1
8
